### ISSUE TITLE
Nav bar structure & titles

### ISSUE THREAD

**Issue by francesca-sp** [OuiShare/OuiShare#164]
@barboza as you know there has been a LOT of back and forth regarding the content in the nav bar of the site (and I am sorry for that), so it seems to be we need to find a permanent solution for managing this, because there will always be changes. 

Unless you don't mind me asking you to change what the nav bar item say (other than events and projects), it would be good if there was a way for us to at least edit the name of the items in the nav bar. It is just too hard for us to know how it will need to look in the future, so cannot really ever give you a "final nav bar" that won't change (if you know what I mean). 

So - can we make it editable? We cannot change the titels from transifex, can we?

Apart from that, could we add one item in the first dropdown on the top (ABOUT), called "about us", which links to the about page? It seems that people have not been able to find the about page, because not everyone clicks on the top nav bar. And since this is almost the most important page on the site, we really need it to appear in the dropdown itself. 

thank you for your patience :)

**Comment by kirilind** [comment]
Navbar rearranged and labels updated in 2015.
https://github.com/OuiShare/OuiShare/blob/master/app/views/layouts/_header.html.slim

Admin (backend) navbar arrangement and texts brought up-to-date with website (frontend) as well.
https://github.com/OuiShare/OuiShare/blob/master/app/views/layouts/_admin_header.html.slim
