### ISSUE TITLE
SEO and search results not ok

### ISSUE THREAD

**Issue by francesca-sp** [OuiShare/OuiShare#170]
When you a search on OuiShare, the preview of the site is not correct and highlights quite odd parts of the site, see screenshot. 

@barboza @guilhermecomum 
This is an extremely important aspect: could the meta text be adapted to display 4 elements of the top navigation bar and the first sentence in this part? In general, would you like me to tell you exactly what we would like to appear in the preview? 

@ykastelnik @karnaud do you have more experience with how to fix this? 

![image](https://f.cloud.github.com/assets/3641828/2385846/555ec70a-a923-11e3-8159-5298f576d7a3.png)

**Comment by karnaud** [comment]
see #228
