### ISSUE TITLE
Donation system

### ISSUE THREAD

**Issue by pitch-me-git** [OuiShare/OuiShare#183]
See if MangoPay is a good alternative to Paypal regarding fees and tech environment.
1,8%/transaction + 0,18 cts, can be negociated to 1,4% for non-profits, no setup nor monthly fees.
Of course require https.

HelloAsso whould have been great (no fess for NPOs) but only in french

Any alternatives guys ?

**Comment by karnaud** [comment]
can we close ?

**Comment by kirilind** [comment]
:+1: for Stripe, adding to further developments batch

**Comment by kirilind** [comment]
using HelloAsso
