### ISSUE TITLE
Events page : Changing the layout

### ISSUE THREAD

**Issue by pitch-me-git** [OuiShare/OuiShare#184]
Visualisation of the events in a nice calendar instead of a text list.

Let's find a nice calendar component.
Here are some i found :

http://arshaw.com/fullcalendar/
http://kylestetz.github.io/CLNDR/

http://codecanyon.net/item/booking-calendar-pro-jquery-plugin/full_screen_preview/244645
http://codecanyon.net/item/jquery-flat-event-calendar-responsive-timeline/full_screen_preview/6039142

**Comment by kirilind** [comment]
Events slider implemented with design update in July 2015, closing it for now until further needs defined.
