### ISSUE TITLE
website contact form not working

### ISSUE THREAD

**Issue by kirilind** [OuiShare/OuiShare#219]
it seems there's an issue with ouishare contact form , we don't receive emails that are sent through it, since 2/3 months (02/2015)

How is the form sending mails?

**Comment by kirilind** [comment]
[According to these settings](https://github.com/OuiShare/OuiShare/blob/master/app/views/contact/_form.html.slim) one has to precise sender address that is verified, but I don't see to: address defined anywhere.
Mailer controller: https://github.com/OuiShare/OuiShare/blob/master/app/mailers/contact_mailer.rb

**Comment by kirilind** [comment]
Ah! According to this https://github.com/OuiShare/OuiShare/blob/master/app/controllers/contact_controller.rb the form selects receiver address by dropdown (countries), and sends to hello@ by default. All listed email addresses exist an function since the mails move.

As the allowed "sender" servers are defined in MX records, maybe the contact form mails go to spam? What server are they sent from?

**Comment by kirilind** [comment]
Tried to send a test mail to France, on submit displays blank page on http://ouishare.net/en/contact

**Comment by pitch-me-git** [comment]
The problem come from two things : 
- filter on countries
- bad settings in https://github.com/OuiShare/OuiShare/blob/master/config/initializers/mailer.rb

You were sending emails from SENDGRID and not from webfaction

**Comment by pitch-me-git** [comment]
third things : the email was sending from de email params in the form.
So for gmail address, it was asking to use gmail SMTP

**Comment by karnaud** [comment]
ca we close ?
