### ISSUE TITLE
display twitter links conditionally based on site language

### ISSUE THREAD

**Issue by karnaud** [OuiShare/OuiShare#231]
need to have the list of twitter links

**Comment by kirilind** [comment]
EN/default: https://twitter.com/OuiShare
FR: https://twitter.com/OuiShare_Fr
DE: https://twitter.com/OuiShare_de
ES: https://twitter.com/OuiShare_es
IT: https://twitter.com/OuiShare_it

**Comment by karnaud** [comment]
done both in footer and header
link in yml file
