### ISSUE TITLE
events selection on community edit page  : autocomplete

### ISSUE THREAD

**Issue by karnaud** [OuiShare/OuiShare#232]
like in the backend, look at "edit profile" language selection model

**Comment by karnaud** [comment]
Like Contact me in on User edit profile

![capture du 2015-12-01 09 55 18](https://cloud.githubusercontent.com/assets/3533688/11496372/ae5719be-9811-11e5-9587-f441a0847e33.png)

**Comment by kirilind** [comment]
it still needs the ability to delete the selected events from X, right? 

<img width="805" alt="screen shot 2015-12-02 at 00 05 04" src="https://cloud.githubusercontent.com/assets/4502647/11518363/6d4104fe-9888-11e5-8a3a-3b045438ce81.png">

**Comment by karnaud** [comment]
yes done :-)
