### ISSUE TITLE
nice URLs for communities

### ISSUE THREAD

**Issue by kirilind** [OuiShare/OuiShare#242]
Create automatic permalinks for communities. 
Currently: http://ouishare.net/community/[id] (http://ouishare.net/community/8 )
Change to: http://ouishare.net/city (template http://ouishare.net/[title] ) > http://ouishare.net/paris

**Comment by ykastelnik** [comment]
After going live we'll have to save again all communities to generate slugs with this script:

`Community.find_each(&:save)`

**Comment by kirilind** [comment]
how should we proceed with new community URLs in regard to redirects?

> One "easy" way to do so would be to create those urls in the code and then add a permanent redirection to the full URL (to avoid duplicate content for SEO).

As said just before:
> On the technical side it will be tough to find a way to have multiple types of entities (communities, projects) on the root path (ouishare.net/xxx) as all the routing system would need to be adapted. 
/ Yann
