### ISSUE TITLE
http://ouishare.net/en/newsletter/subscribe

### ISSUE THREAD

**Issue by kirilind** [OuiShare/OuiShare#244]
Adding an address to mailinglist subscribe leads to page
http://ouishare.net/en/newsletter/subscribe 
which gives server error 500.

**Comment by kirilind** [comment]
<img width="941" alt="screen shot 2015-12-01 at 10 56 37" src="https://cloud.githubusercontent.com/assets/4502647/11497584/3dd9b85a-981a-11e5-9485-7b686b207027.png">

(subscription via the link in the footer)

**Comment by karnaud** [comment]
see #238

**Comment by karnaud** [comment]
it's related to your mailchimp key with Gibbon
http://cheshireoctopus.github.io/blog/2014/01/23/mailchimp-plus-gibbon-plus-rails-create-a-basic-sign-up-form/

**Comment by karnaud** [comment]
change version of gibbon gem
```
Using gibbon 1.1.6 (was 2.0.0)
```
