### ISSUE TITLE
user association field format

### ISSUE THREAD

**Issue by kirilind** [OuiShare/OuiShare#250]
Current format for users association field in the backend is a dropdown list:
<img width="871" alt="screen shot 2016-01-12 at 15 03 26" src="https://cloud.githubusercontent.com/assets/4502647/12265500/adfca61c-b93d-11e5-8919-872a0f87623d.png">

Change the field format into autocomplete with suggestions, like in the Search field on [search page](http://ouishare.net/en/search):
<img width="948" alt="screen shot 2016-01-12 at 15 01 44" src="https://cloud.githubusercontent.com/assets/4502647/12265491/9a12bb96-b93d-11e5-9801-7fecb0901a12.png">
[See code for search page](https://github.com/OuiShare/OuiShare/blob/staging/app/views/search/search.html.slim#L12)

Alternative:
Add datatable view like in the [users list in backend](https://github.com/OuiShare/OuiShare/blob/staging/app/views/admin/users/index.html.slim#L25)

Change in:
- [projects edit](https://github.com/OuiShare/OuiShare/blob/staging/app/views/admin/projects/_form.html.slim#L41)
- [events edit](https://github.com/OuiShare/OuiShare/blob/staging/app/views/admin/events/_form.html.slim)
- [communities edit](https://github.com/OuiShare/OuiShare/blob/staging/app/views/admin/communities/_form.html.slim#L30)

**Comment by karnaud** [comment]
for autocomplete on event page : 
<img width="899" alt="capture d ecran 2017-02-07 a 12 34 56" src="https://cloud.githubusercontent.com/assets/3533688/22689580/e483ff4a-ed31-11e6-940c-78646bc31f7f.png">

**Comment by kirilind** [comment]
Great, looking good!

There's still Community (City) page to do, [e.g. here](http://ouishare.pitchme.webfactional.com/en/admin/languages/1/communities/8/edit) > see code https://github.com/OuiShare/OuiShare/blob/staging/app/views/admin/communities/_form.html.slim#L22-L36

Also would it be possible to keep the [helper text strings](https://github.com/OuiShare/OuiShare/commit/03690556f5c28d1c3542eb9dd468749814c7d3fe#diff-c2cc829fa25215f8cb7b1362dc487ab8L59) as strings, instead of changing them to [non-translatable labels](https://github.com/OuiShare/OuiShare/commit/03690556f5c28d1c3542eb9dd468749814c7d3fe#diff-c2cc829fa25215f8cb7b1362dc487ab8R64)?

**Comment by kirilind** [comment]
community connectors old style:
<img width="982" alt="screen shot 2017-02-07 at 22 07 49" src="https://cloud.githubusercontent.com/assets/4502647/22709292/fd18b64a-ed81-11e6-86ba-e6992e904312.png">
