### ISSUE TITLE
user profile visibility

### ISSUE THREAD

**Issue by kirilind** [OuiShare/OuiShare#287]
Add checkbox field “visible” to user profile
If unchecked, profile is not displayed in public (is displayed only to logged in users)
- [x] add field in db
- [x] display checkbox on user profile
- [x] display checkbox on user admin page
- [ ] ~~add conditional to member profile that displays a "not accessible" note when field is unchecked~~
- [x] if field not checked, profile accessible behind login wall

**Comment by karnaud** [comment]
test with http://ouishare.pitchme.webfactional.com/en/profile/rafael-barboza

`Visible: false`

Visible when current user, not visible where not connected

<img width="634" alt="capture d ecran 2017-02-07 a 10 34 07" src="https://cloud.githubusercontent.com/assets/3533688/22685547/ff92b45e-ed20-11e6-938a-ba373d0a20e6.png">
