### ISSUE TITLE
events association field format

### ISSUE THREAD

**Issue by kirilind** [OuiShare/OuiShare#293]
Current format for users association field in the backend is a dropdown list:
<img width="1199" alt="screen shot 2017-01-31 at 19 36 40" src="https://cloud.githubusercontent.com/assets/4502647/22476903/b0da5800-e7ec-11e6-8c97-9179f30cdfd6.png">

- Change the field format on [community edit page](https://github.com/OuiShare/OuiShare/blob/staging/app/views/admin/communities/_form.html.slim#L55) into autocomplete with suggestions 

- **Add a reverse of this association to [event edit page](https://github.com/OuiShare/OuiShare/blob/staging/app/views/admin/events/_form.html.slim#L78)** after "Organizers", allowing to find and add communities to the event

see also #250

**Comment by karnaud** [comment]
Done

For event on community page : 
<img width="1050" alt="capture d ecran 2017-02-07 a 12 27 50" src="https://cloud.githubusercontent.com/assets/3533688/22689355/eb1f2786-ed30-11e6-8f75-c4ff3c7315de.png">

For community on event page : 
<img width="880" alt="capture d ecran 2017-02-07 a 12 29 05" src="https://cloud.githubusercontent.com/assets/3533688/22689373/0ec4c056-ed31-11e6-9684-34624c48a99d.png">
