### ISSUE TITLE
items order in region and cities dropdown

### ISSUE THREAD

**Issue by kirilind** [OuiShare/OuiShare#294]
In region and community (cities) dropdowns, order items alphabetically (by title / name)

- https://github.com/OuiShare/OuiShare/blob/staging/app/views/communities/index.html.slim#L15-L16

**Comment by karnaud** [comment]
For region : 
<img width="404" alt="capture d ecran 2017-02-07 a 12 30 32" src="https://cloud.githubusercontent.com/assets/3533688/22689431/54e7b8c2-ed31-11e6-988c-4e44367cbafd.png">

For cities : 
<img width="849" alt="capture d ecran 2017-02-07 a 12 30 46" src="https://cloud.githubusercontent.com/assets/3533688/22689439/5c1466ea-ed31-11e6-9c02-bfbd91b4160d.png">
